apiVersion: v1
kind: Service
metadata:
  name: ai-home-designer-service
spec:
  selector:
    app: ai-home-designer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer